name: Deploy para GitHub Pages

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Injetar chave da API no api.js
        run: |
          CHAVE_BASE64=$(echo -n "${{ secrets.OMDBAPIKEY }}" | base64)
          sed -i "s/CHAVE_PADRAO = \"[^\"]*\"/CHAVE_PADRAO = atob(\"$CHAVE_BASE64\")/" js/api.js

      - name: Deploy para gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
